
// This file has been generated by the GUI designer. Do not modify.
public partial class MainWindow
{
	private global::Gtk.UIManager UIManager;
	private global::Gtk.Action FileAction;
	private global::Gtk.Action newAction;
	private global::Gtk.Action loadAction;
	private global::Gtk.VBox VBoxMain;
	private global::Gtk.MenuBar menubar1;
	private global::Gtk.HBox hbox1;
	private global::Gtk.VBox TileVBox;
	private global::Gtk.Table table2;
	private global::Gtk.Button LoadTilesetButton;
	private global::Gtk.ScrolledWindow TileWindow;
	private global::Gtk.VBox vbox6;
	private global::Gtk.Statusbar statusbar2;

	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.UIManager = new global::Gtk.UIManager ();
		global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup ("Default");
		this.FileAction = new global::Gtk.Action ("FileAction", global::Mono.Unix.Catalog.GetString ("File"), null, null);
		this.FileAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("File");
		w1.Add (this.FileAction, null);
		this.newAction = new global::Gtk.Action ("newAction", global::Mono.Unix.Catalog.GetString ("new"), null, null);
		this.newAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("new");
		w1.Add (this.newAction, null);
		this.loadAction = new global::Gtk.Action ("loadAction", global::Mono.Unix.Catalog.GetString ("load"), null, null);
		this.loadAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("load");
		w1.Add (this.loadAction, null);
		this.UIManager.InsertActionGroup (w1, 0);
		this.AddAccelGroup (this.UIManager.AccelGroup);
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.VBoxMain = new global::Gtk.VBox ();
		this.VBoxMain.Name = "VBoxMain";
		this.VBoxMain.Spacing = 6;
		// Container child VBoxMain.Gtk.Box+BoxChild
		this.UIManager.AddUiFromString ("<ui><menubar name='menubar1'><menu name='FileAction' action='FileAction'><menuitem name='newAction' action='newAction'/><menuitem name='loadAction' action='loadAction'/></menu></menubar></ui>");
		this.menubar1 = ((global::Gtk.MenuBar)(this.UIManager.GetWidget ("/menubar1")));
		this.menubar1.Name = "menubar1";
		this.VBoxMain.Add (this.menubar1);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.VBoxMain [this.menubar1]));
		w2.Position = 0;
		w2.Expand = false;
		w2.Fill = false;
		// Container child VBoxMain.Gtk.Box+BoxChild
		this.hbox1 = new global::Gtk.HBox ();
		this.hbox1.Name = "hbox1";
		this.hbox1.Spacing = 6;
		// Container child hbox1.Gtk.Box+BoxChild
		this.TileVBox = new global::Gtk.VBox ();
		this.TileVBox.Name = "TileVBox";
		this.TileVBox.Spacing = 6;
		// Container child TileVBox.Gtk.Box+BoxChild
		this.table2 = new global::Gtk.Table (((uint)(3)), ((uint)(3)), false);
		this.table2.Name = "table2";
		this.table2.RowSpacing = ((uint)(6));
		this.table2.ColumnSpacing = ((uint)(6));
		// Container child table2.Gtk.Table+TableChild
		this.LoadTilesetButton = new global::Gtk.Button ();
		this.LoadTilesetButton.CanFocus = true;
		this.LoadTilesetButton.Name = "LoadTilesetButton";
		this.LoadTilesetButton.UseUnderline = true;
		this.LoadTilesetButton.Label = global::Mono.Unix.Catalog.GetString ("load");
		this.table2.Add (this.LoadTilesetButton);
		global::Gtk.Table.TableChild w3 = ((global::Gtk.Table.TableChild)(this.table2 [this.LoadTilesetButton]));
		w3.LeftAttach = ((uint)(2));
		w3.RightAttach = ((uint)(3));
		w3.XOptions = ((global::Gtk.AttachOptions)(4));
		w3.YOptions = ((global::Gtk.AttachOptions)(4));
		this.TileVBox.Add (this.table2);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.TileVBox [this.table2]));
		w4.Position = 0;
		// Container child TileVBox.Gtk.Box+BoxChild
		this.TileWindow = new global::Gtk.ScrolledWindow ();
		this.TileWindow.CanFocus = true;
		this.TileWindow.Name = "TileWindow";
		this.TileWindow.ShadowType = ((global::Gtk.ShadowType)(1));
		this.TileVBox.Add (this.TileWindow);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.TileVBox [this.TileWindow]));
		w5.Position = 1;
		this.hbox1.Add (this.TileVBox);
		global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.TileVBox]));
		w6.Position = 0;
		// Container child hbox1.Gtk.Box+BoxChild
		this.vbox6 = new global::Gtk.VBox ();
		this.vbox6.Name = "vbox6";
		this.vbox6.Spacing = 6;
		this.hbox1.Add (this.vbox6);
		global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.vbox6]));
		w7.Position = 2;
		this.VBoxMain.Add (this.hbox1);
		global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.VBoxMain [this.hbox1]));
		w8.Position = 1;
		// Container child VBoxMain.Gtk.Box+BoxChild
		this.statusbar2 = new global::Gtk.Statusbar ();
		this.statusbar2.Name = "statusbar2";
		this.statusbar2.Spacing = 6;
		this.VBoxMain.Add (this.statusbar2);
		global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.VBoxMain [this.statusbar2]));
		w9.Position = 2;
		w9.Expand = false;
		w9.Fill = false;
		this.Add (this.VBoxMain);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 973;
		this.DefaultHeight = 656;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.LoadTilesetButton.Clicked += new global::System.EventHandler (this.OnLoadTilesetButtonClicked);
	}
}
